[tool.poetry]
name = "p360_ga_downloader"
version = "0.2.3"
description = "Extractor for Google analytics"
readme = "README.md"
repository = "https://github.com/DataSentics/GA_Extractor"

license = "MIT"

authors = [
    "Roman Novosad <roman.novosad@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

packages = [
    { include = "ga", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10.0"
requests = "^2.25.1"
google-auth = "^1.30.0"
wrapt = "^1.12.1"
google-cloud = "^0.34.0"
google-cloud-bigquery = "^2.26.0"
google-cloud-storage = "^1.42.2"
azure-storage-blob = "^12.9.0"
azure-identity = "^1.7.0"

[tool.poetry.dev-dependencies]
pylint = "2.4.*"
pytest = "5.2.*"
flake8 = "^3.9.1"
black = "^20.8b1"
poethepoet = "^0.10.0"

[tool.black]
line-length = 140

[tool.poe.tasks]
black = "black src"
black-check = "black --check src"
flake8 = "flake8 --ignore=E501,W503 src"

[[tool.poetry.source]]
name = "datasentics"
url = "https://pkgs.dev.azure.com/dataengineerics/_packaging/dataengineerics/pypi/simple/"
secondary = true

