[tool.poetry]
name = "aerismodsdk"
version = "0.1.5"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
pyusb = "^1.0.2"
pyserial = "^3.4"
"RPi.GPIO" = "^0.7.0"
xmodem = "^0.4.5"
pyjwt = "^1.7.1"
cryptography = "^3.0"
requests = "^2.24.0"
urllib3 = "^1.26.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pycodestyle = "^2.5.0"
pylint = "^2.4.4"

[tool.poetry.scripts]
aeriscli = "aerismodsdk.cli:mycli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

