[tool.poetry]
name = "slurmer"
version = "1.0.6"
description = "A package to schedule different tasks in parallel with cluster support."
authors = ["Joan Marc√® i Igual <J.Marce.i.Igual@tue.nl>"]
readme = "README.md"
license = "MIT"
homepage = "https://jmigual.github.io/slurmer/"
repository = "https://github.com/jmigual/slurmer"

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flakehell = "^0.9.0"
flake8 = "3.9.2"
flake8-bandit = "^2.1.2"
flake8-builtins = "^1.5.3"
flake8-bugbear = "^21.11.29"
flake8-comprehensions = "^3.8.0"
flake8-docstrings = "^1.6.0"
flake8-eradicate = "^1.2.0"
flake8-isort = "^4.1.1"
flake8-mutable = "^1.2.0"
flake8-pytest-style = "^1.6.0"
flake8-deprecated = "^1.3"
darglint = "^1.8.1"
mccabe = "^0.6.1"
pep8-naming = "^0.12.1"
pycodestyle = "2.7.0"
pyflakes = "2.3.1"
pylint = "^2.12.2"
black = "^20.8b1"
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"
sphinx-autodoc-typehints = "^1.17.0"

[tool.flakehell]
exclude = ['README.md']
max_line_length = 100
format = 'colored'
extended_default_ignore= [] # add this to fix issue in flakehell

[tool.flakehell.plugins]
flake8-bandit = ["+*", "-S322"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-docstrings = ["+*"]
flake8-eradicate = ["+*"]
flake8-isort = ["+*"]
flake8-mutable = ["+*"]
flake8-pytest-style = ["+*"]
flake8-deprecated = ["+*"]
darglint = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]

[tool.black]
line-length = 100


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
