[tool.poetry]
name = "macad"
version = "1.0.1"
description = "The Tool For Changing Your MAC Address for Any Interface"
authors = ["Deepak Patidar <info.deepakpatidar@gmail.com>"]
license = "MIT"
repository = 'https://github.com/DeepakDarkiee/macad.git'
readme = 'README.md'
keywords = ['mac-address','macad','mac-changer']

[tool.poetry.dependencies]
python =  ">= 3.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
macad = "macad.mac_changer:main"
