[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["Zakkai Thomas <zmanmustang2017@gmail.com>"]
description = "Automatic equation solver."
name = "eqsolvcarlover101"
version = "0.1.6.1"
[tool.poetry.dependencies]
python = "^3.8"
[tool.poetry.dev-dependencies]
